src/Blocks/Measure.jl, src/Interfaces/Measure.jl, src/Registers/Default.jl, src/Registers/Measure.jl, src/Registers/Registers.jl, test/Blocks/Measure.jl, test/Interfaces/Interfaces.jl, test/Registers/Default.jl
This PR brings two changes
e.g. 
```julia
julia> rs = rand_state(4,3)
DefaultRegister{3, Complex{Float64}}
active qubits: 4/4
julia> rs .|> Ref(put(4, 1=>X))
(DefaultRegister{1, Complex{Float64}}
active qubits: 4/4, DefaultRegister{1, Complex{Float64}}
active qubits: 4/4, DefaultRegister{1, Complex{Float64}}
active qubits: 4/4)
```
Which can be useful in implementing some algorithms require reuable qubits, like the one in
> Towards Quantum Machine Learning with Tensor Networks
> William Huggins, Piyush Patel, K. Birgitta Whaley, E. Miles Stoudenmire
> https://arxiv.org/abs/1803.11537
usage:
```julia
reg = rand_state(4)
mb = MeasureAndReset(3)
reg |> mb
@test all(measure(reg, 10) .== 3)
```
=> broadcast register & measure_reset!

lib/YaoBase/src/abstract_register.jl, src/deprecations.jl
let's not deprecate the qubits interfaces, they are not identical to the qudits. It's still necessary to have them. I think it's important to let users who only wants to deal with qubits to stay in qubits land
Also @GiggleLiu let's not use so much `import`s and actually try not to use `import` at all in the future, it's very painful when you try to find if a method is overloaded or created as new function for issues like this.
=> fix warning & rm wrong depwarn

lib/YaoSym/src/symengine/register.jl, lib/YaoSym/test/symengine/blocks.jl
The `_pretty_basic` call mixes original element matrix type. By default `S` gate matrix is
```julia
julia> mat(S)
2×2 LinearAlgebra.Diagonal{ComplexF64, Vector{ComplexF64}}:
1.0+0.0im      ⋅    
⋅      0.0+1.0im
```
but `mat(Bacis, S)` returns `Number`-typed matrix 
```julia
julia> mat(Bacis, S)
2×2 Matrix{Number}:
1   0
0  im
```
This makes impossible to use matrix multiplication.
```julia
julia> q
2×1 SparseArrays.SparseMatrixCSC{Basic, Int64} with 2 stored entries:
(1/2)*sqrt(2)
(1/2)*sqrt(2)
julia> mat(Bacis, S) * q.state
MethodError: no method matching zero(::Type{Any})
Closest candidates are:
zero(::Type{Union{Missing, T}}) where T at ~/Applications/julia-1.7.2/share/julia/base/missing.jl:105
zero(::Union{Type{P}, P}) where P<:Dates.Period at …
```
=> Enforce `Matrix{Basic}` type during conversion

docs/Project.toml, docs/src/examples/4.shor-algorithm/main.jl, docs/src/quick-start.md, lib/YaoAPI/src/blocks.jl, lib/YaoBlocks/src/abstract_block.jl, lib/YaoBlocks/src/composite/chain.jl, lib/YaoBlocks/src/composite/control.jl, lib/YaoBlocks/src/composite/kron.jl, lib/YaoBlocks/src/composite/put_block.jl, lib/YaoBlocks/src/composite/reduce.jl, lib/YaoBlocks/src/composite/repeated.jl, lib/YaoBlocks/src/composite/subroutine.jl, lib/YaoBlocks/src/composite/tag/cache.jl, lib/YaoBlocks/src/composite/tag/scale.jl, lib/YaoBlocks/src/composite/unitary_channel.jl, lib/YaoBlocks/src/primitive/measure.jl, lib/YaoBlocks/src/primitive/rotation_gate.jl, lib/YaoBlocks/src/primitive/time_evolution.jl, lib/YaoBlocks/test/composite/cache.jl, src/EasyBuild/block_extension/blocks.jl
as we discussed last week, I want to have this before fixing https://github.com/QuEraComputing/Bloqade.jl/issues/323
=> export unsafe_apply as the overload interface

lib/YaoBlocks/src/layout.jl, lib/YaoBlocks/src/primitive/general_matrix_gate.jl, src/EasyBuild/hamiltonians.jl, test/easybuild/hamiltonians.jl
```julia
julia> function rydberg_chain(nbits::Int; Ω::Number=0.0, Δ::Real=0.0, V::Real=0.0, r::Real=0.0)
Pr = matblock(sparse([3], [3], [1.0+0im], 3, 3); nlevel=3, tag="|r⟩⟨r|")
Z1r = matblock(sparse([2, 3], [2, 3], [1.0+0im, -1.0], 3, 3); nlevel=3)
X1r = matblock(sparse([2, 3], [3, 2], [1.0+0im, 1.0], 3, 3); nlevel=3, tag="|1⟩⟨r| + |r⟩⟨1|")
X01 = matblock(sparse([1, 2], [2, 1], [1.0+0im, 1.0], 3, 3); nlevel=3, tag="|1⟩⟨0| + |0⟩⟨1|")
Y1r = matblock(sparse([3, 2], [2, 3], [1.0im, -1.0im], 3, 3); nlevel=3, tag="i|1⟩⟨0| - i|0⟩⟨1|")
h = Add(nbits; nlevel=3)
!isapprox(Δ, 0; atol=1e-12) && push!(h, (-Δ) * sum([put(nbits, i=>Pr) for i=1:nbits]))
#!iszero(Δ) && push!(h, (-Δ/2) * sum([put(nbits, i=>Z1r) for i=1:nbits]))
!isapprox(real(Ω), 0; atol=1e-12) && push!(h, real(Ω)/2 * sum([put(nbits, …
```
=> specify matblock printing

lib/YaoBlocks/src/autodiff/chainrules_patch.jl, lib/YaoBlocks/test/autodiff/chainrules_patch.jl
The `sum` and `put` constructors are still not properly supported.
Zygote dispatches these functions to incorrect backward rules.
I do not have time to fix all interfaces, after all, the AD engine should be able to figure out the incorrect backward rules specification.
@VarLad
=> fix ad error for abstract vector constructors

lib/YaoBlocks/src/primitive/const_gate_tools.jl
I had to read the sources to find out how to create a const_gate that acts on qutrits instead of qubits. To make it simpler for the next person I added some details to the docstring  of the const_gate macro.
=> Clarified documentation of @const_gate by adding a description of the nlevel=D option

lib/YaoBlocks/src/routines.jl, lib/YaoBlocks/test/rountines.jl
MWE:
before
```julia
julia> using YaoBlocks, BitBasis
[ Info: Precompiling YaoBlocks [418bc28f-b43b-5e0b-a6e7-61bbc1a2c1df]
julia> YaoBlocks.unsafe_getcol(ComplexF64, put(5, 1=>ConstGate.P1), bit"00000")
(Any[], ComplexF64[])
```
after
```julia
julia> using YaoBlocks, BitBasis
julia> YaoBlocks.unsafe_getcol(ComplexF64, put(5, 1=>ConstGate.P1), bit"00000")
(DitStr{2, 5, Int64}[], ComplexF64[])
```
=> fix type stability

lib/YaoBlocks/src/autodiff/chainrules_patch.jl, lib/YaoBlocks/src/autodiff/specializes.jl, lib/YaoBlocks/test/autodiff/specializes.jl
Up until now `expect_g` and `fidelity_g` were off by a factor of one half, in the sense that 
∂_reg expect(ham, reg) = 2 * expect_g(ham, reg) instead ∂_reg expect(ham, reg) = expect_g(ham, reg) and analogous for the other methods of `expect_g` and `fidelity_g`. This was counter acted by multiplying a factor of 2 to the final `paramsδ` at the end of `expect_g(ham, reg => circuit)` and `fidelity_g(reg1 => circuit1, reg2 => circuit2)`.
This is changed here to backpropagate the "correctly" scaled gradient w.r.t registers.
I am not sure if this would be considered a breaking change, because it also means that the output of `expect'(ham, reg => circuit)[1]` is changed by a factor of 2 now. 
Changes: 
- Changed expect_g and fidelity_g
- Updated the rrules in chainrules_patch.jl
- Updated the …
=> Changed expect_g and fidelity_g to return the "correctly" scaled gradient w.r.t to the register

lib/YaoArrayRegister/src/density_matrix.jl, lib/YaoArrayRegister/test/density_matrix.jl
The title says it all. I also checked that #416 and #408 don't add `similar(::DensityMatrix)`
=> Added similar(::DensityMatrix)

lib/YaoBlocks/src/channel/error_channel.jl, lib/YaoBlocks/test/channel/error_channel.jl
and changed meaning of `p` in `bit_flip_channel` and `phase_flip_channel` to be consistent with the other error channels
Changes to be committed:
modified:   lib/YaoBlocks/src/channel/error_channel.jl
modified:   lib/YaoBlocks/test/channel/error_channel.jl
=> Added docstring to `pauli_error_channel()`

lib/YaoBlocks/Project.toml, lib/YaoBlocks/src/composite/kron.jl
Previously to this PR we had that 
```julia
using Yao
kb1 = kron(3, 1 => X)
kb2 = kron(3, 1=>X, 2=>Z)
kb3 = kron(3, 1=>X, 2=>Z, 3=>Y)
kb1 == kb2
false  # as one would expect
kb2 == kb3
ERROR: DimensionMismatch: arrays could not be broadcast to a common size; got a dimension with lengths 2 and 3
```
This is fixed with this PR.
=> Fixed KronBlock equality check

lib/YaoBlocks/Project.toml, lib/YaoBlocks/src/autodiff/apply_back.jl, lib/YaoBlocks/src/autodiff/chainrules_patch.jl, lib/YaoBlocks/src/blocktools.jl, lib/YaoBlocks/test/autodiff/chainrules_patch.jl
@Roger-luo we need to release a patch fix since a student needs to use this feature for development.
=> fix autodiff apply, fix a docstring error

lib/YaoArrayRegister/src/instruct.jl, lib/YaoSym/Project.toml, lib/YaoSym/src/YaoSym.jl, lib/YaoSym/src/register.jl, lib/YaoSym/src/symengine/blocks.jl, lib/YaoSym/src/symengine/instruct.jl, lib/YaoSym/src/symengine/patch.jl, lib/YaoSym/src/symengine/register.jl, lib/YaoSym/src/symengine/symengine.jl, lib/YaoSym/test/symengine/blocks.jl
This PR fixes the previous incorrect symbolic abs function. Depends on another PR to be merged: https://github.com/symengine/SymEngine.jl/pull/267
This PR also explicitly add the SymEngine as the dependency. I notice that two minor versions has been released, and it seems most stasbility issue in SymEngine has been resolved.
=> Fix symbolic abs function

Project.toml, ext/CuYao/src/CuYao.jl, ext/CuYao/src/yao2einsum.jl, ext/CuYao/test/runtests.jl, ext/CuYao/test/yao2einsum.jl, lib/YaoToEinsum/Project.toml
fix #505 
In this PR,
- I moved the CUDA extension of YaoToEinsum to CuYao.
- Restored the `[weakdeps]` and `[extensions]` sections that removed in a previous commit.
=> Fix CUDA extension - Project.toml

lib/YaoBlocks/src/utils.jl, lib/YaoBlocks/test/blocktools.jl, lib/YaoBlocks/test/utils.jl
fix #508 by setting a looser threshold.
=> Fix issue 508

docs/src/man/registers.md, lib/YaoBlocks/test/primitive/time_evolution.jl, lib/YaoPlots/Project.toml, lib/YaoPlots/README.md, lib/YaoPlots/src/3d.jl, lib/YaoPlots/src/YaoPlots.jl, lib/YaoPlots/src/bloch.jl, lib/YaoPlots/src/helperblock.jl, lib/YaoPlots/src/vizcircuit.jl, lib/YaoPlots/test/helperblock.jl, lib/YaoPlots/test/vizcircuit.jl
```julia
julia> c = chain(put(5, 2=>X), put(5, 2=>line_annotation("!!!"; color="green")),  put(5, 3=>Y), control(5, 2, 3=>X))
nqubits: 5
chain
├─ put on (2)
│  └─ X
├─ put on (2)
│  └─ !!!
├─ put on (3)
│  └─ Y
└─ control(2)
└─ (3,) X
julia> vizcircuit(c)
```
=> Annotate a single line (for quantum error correction)

lib/YaoAPI/src/registers.jl, lib/YaoArrayRegister/src/density_matrix.jl, lib/YaoArrayRegister/src/measure.jl, lib/YaoArrayRegister/src/operations.jl, lib/YaoArrayRegister/test/density_matrix.jl, lib/YaoBlocks/src/autodiff/autodiff.jl, lib/YaoBlocks/src/autodiff/chainrules_patch.jl, lib/YaoBlocks/src/measure_ops.jl, lib/YaoBlocks/test/autodiff/chainrules_patch.jl, lib/YaoBlocks/test/measure_ops.jl
Fix #531 
- Measure density matrix inplace, support reset and remove post-processing.
- Measure operators on density matrix.
=> Measure density matrix inplace

lib/YaoArrayRegister/src/density_matrix.jl, lib/YaoArrayRegister/test/density_matrix.jl
This PR fixes collapseto! to normalize density matrices properly, based on #534. Adds a warning when collapse results in a near-zero probability state. A test is added to ensure normalization remains valid in these cases.
=> Fix collapseto! normalization and add test for mixed states

lib/YaoPlots/src/vizcircuit.jl
These should probably have errored on earlier julia versions
Ref https://github.com/JuliaLang/julia/issues/57334#event-16251080756
=> Remove unnecessary const declarations when setting a ref
