appveyor.yml
src/Cache/Cache.jl

We will not support v0.7 & Windows until v0.2.

WIP: Windows & v0.7 compatibility

---

src/Intrinsics/Math.jl
test/Intrinsics/Math.jl

@JeffreySarnoff I used your implementation here. Thanks.

Better Log2i

---

examples/QFT.jl
src/Blocks/Control.jl
src/Boost/Control.jl

control gate happened to be dispatched to some in efficient functions.

fix control gate

---

src/Blocks/PutBlock.jl

fix put block bounds check

---

src/Interfaces/Candies.jl
src/Interfaces/Interfaces.jl
src/Registers/Core.jl
src/Registers/Default.jl
src/Registers/Registers.jl
test/Interfaces/Candies.jl
test/Interfaces/Interfaces.jl
test/Registers/Default.jl

Eye candies
* reg |> block, an alias for applying blocks.
* reg1 $\otimes$ reg2, join two registers.

Add eye candies

---

docs/src/tutorial/Diff.md
docs/src/tutorial/QCBM.md
src/Blocks/Concentrator.jl
src/Blocks/Container.jl
src/Blocks/Core.jl
src/Blocks/Diff.jl
src/Blocks/blockoperations.jl
src/Interfaces/Interfaces.jl
src/Interfaces/TagBlock.jl
src/Registers/Core.jl
src/Registers/Default.jl
test/Blocks/ChainBlock.jl
test/Blocks/RotationGate.jl
test/Interfaces/TagBlock.jl

* bug fix
* opdiff
* vstatdiff
```julia
opdiff(psifunc, diffblock::AbstractDiff, op::MatrixBlock)
vstatdiff(psifunc, diffblock::AbstractDiff, vstat::Vstat; p0)
```
going to optimize QCBM doc!

Differentiation for V-statistics

---

README.md

rm warning

---

lib/YaoSym/.github/workflows/CI.yml
lib/YaoSym/.github/workflows/CompatHelper.yml
lib/YaoSym/.github/workflows/TagBot.yml
lib/YaoSym/.github/workflows/format-pr.yml
lib/YaoSym/.gitignore
lib/YaoSym/LICENSE
lib/YaoSym/Project.toml
lib/YaoSym/README.md
lib/YaoSym/docs/Project.toml
lib/YaoSym/docs/make.jl
lib/YaoSym/docs/src/index.md
lib/YaoSym/example/symad.jl
lib/YaoSym/example/symad2.jl
lib/YaoSym/src/YaoSym.jl
lib/YaoSym/src/register.jl
lib/YaoSym/src/symengine/backend.jl
lib/YaoSym/src/symengine/blocks.jl
lib/YaoSym/src/symengine/instruct.jl
lib/YaoSym/src/symengine/patch.jl
lib/YaoSym/src/symengine/register.jl
lib/YaoSym/test/register.jl
lib/YaoSym/test/runtests.jl
lib/YaoSym/test/symengine/backend.jl
lib/YaoSym/test/symengine/blocks.jl
lib/YaoSym/test/symengine/instruct.jl
lib/YaoSym/test/symengine/register.jl

forgot to include YaoSym in #303

move YaoSym to lib

---

lib/YaoBlocks/src/measure_ops.jl
lib/YaoBlocks/test/measure_ops.jl

fix measuring add block

---

lib/YaoBlocks/src/measure_ops.jl
lib/YaoBlocks/test/measure_ops.jl

let the error message be more intuitive.

error-measure-better

---

lib/YaoBlocks/src/autodiff/chainrules_patch.jl
lib/YaoBlocks/test/autodiff/chainrules_patch.jl

fix 349 and 348

---

lib/YaoBlocks/src/autodiff/specializes.jl
lib/YaoBlocks/test/autodiff/specializes.jl

fix fidelity gradient

---

lib/YaoAPI/src/blocks.jl
lib/YaoArrayRegister/src/register.jl
lib/YaoBlocks/src/composite/chain.jl
lib/YaoBlocks/src/composite/control.jl
lib/YaoBlocks/src/composite/kron.jl
lib/YaoBlocks/src/composite/put_block.jl
lib/YaoBlocks/src/composite/reduce.jl
lib/YaoBlocks/src/composite/unitary_channel.jl
lib/YaoBlocks/src/primitive/const_gate_tools.jl
lib/YaoBlocks/src/primitive/general_matrix_gate.jl
lib/YaoBlocks/src/primitive/identity_gate.jl
lib/YaoBlocks/src/primitive/measure.jl
lib/YaoBlocks/src/primitive/phase_gate.jl
lib/YaoBlocks/src/primitive/rotation_gate.jl
lib/YaoBlocks/src/primitive/shift_gate.jl
lib/YaoBlocks/src/primitive/time_evolution.jl
lib/YaoBlocks/src/utils.jl

```
pkg> dev lib/YaoBlocks lib/YaoAPI lib/YaoArrayRegister lib/YaoSym .
julia> using LiveServer; servedocs(;skip_dirs=["docs/src/assets", "docs/src/generated"])
```

add blocks API docs

---

src/EasyBuild/variational_circuit.jl
test/easybuild/variational_circuit.jl

fix issue #377

---

test/easybuild/hamiltonians.jl

NOTE: To get the correct result, the signs of energies and angle must be flipped.

completes levine-pichler pulse

---

lib/YaoBlocks/src/abstract_block.jl
lib/YaoBlocks/src/composite/chain.jl
lib/YaoBlocks/src/utils.jl
src/EasyBuild/block_extension/FSimGate.jl
src/EasyBuild/google53.jl
src/EasyBuild/qft_circuit.jl
src/EasyBuild/variational_circuit.jl
test/easybuild/variational_circuit.jl

1. Add generic typed interface to EasyBuild circuits.
2. Fix type change in getindex.

fix generic type

---

README.md

I think we should mention this in README and on website etc.

mention community call

---

lib/YaoArrayRegister/src/density_matrix.jl
lib/YaoArrayRegister/src/register.jl
lib/YaoArrayRegister/src/utils.jl
lib/YaoArrayRegister/test/density_matrix.jl

* Fix density matrix fidelity
* Fix and stablize focused state fidelity.

fix density matrix fidelity

---

lib/YaoAPI/src/blocks.jl
lib/YaoBlocks/src/composite/chain.jl
lib/YaoBlocks/src/composite/control.jl
lib/YaoBlocks/src/composite/kron.jl
lib/YaoBlocks/src/composite/put_block.jl
lib/YaoBlocks/src/composite/unitary_channel.jl
lib/YaoBlocks/src/primitive/rotation_gate.jl
lib/YaoBlocks/src/primitive/shift_gate.jl
lib/YaoBlocks/src/primitive/time_evolution.jl
lib/YaoBlocks/src/routines.jl
lib/YaoBlocks/test/composite/control.jl
lib/YaoBlocks/test/rountines.jl

Fix Yao Blocks

---

lib/YaoBlocks/src/composite/chain.jl
lib/YaoBlocks/test/composite/chain.jl

fix ishermitian of chain

---

lib/YaoBlocks/src/primitive/measure.jl
lib/YaoBlocks/test/primitive/measure.jl

update measure location check

---

lib/YaoBlocks/src/primitive/time_evolution.jl

Fix the following MWE
```julia
using CuYao
num_qubits = 20
psi = product_state(num_qubits, 0) |> cu
circuit = chain(num_qubits)
append!(circuit, chain(num_qubits, time_evolve(chain(put(num_qubits, 1=>Z)), 1.0, tol=1e-5, check_hermicity=false)))
psi = psi |> circuit
```
```julia
julia> psi = psi |> circuit
ERROR: GPU compilation of kernel #broadcast_kernel#17(CUDA.CuKernelContext, CUDA.CuDeviceMatrix{ComplexF64, 1}, Base.Broadcast.Broadcasted{CUDA.CuArrayStyle{2}, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}, typeof(*), Tuple{Base.Broadcast.Extruded{CUDA.CuDeviceMatrix{ComplexF64, 1}, Tuple{Bool, Bool}, Tuple{Int64, Int64}}, Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(exp), Tuple{Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, …
```

fix the error of applying diagonal gate to a GPU register.

---

docs/src/examples/1.prepare-ghz-state/index.md

fix typo in 1.prepare-ghz-state/index.md

---

notebooks/getting-started/assignment1.jl

I fixed a few bugs I noticed in the answer checking code and made it more readable.

Assignment updates

---

ext/CuYao/src/register.jl

fix CUDA.sync_threads() in measure!

---

ext/CuYao/src/CUDApatch.jl
ext/CuYao/src/CuYao.jl
ext/CuYao/src/instructs.jl
ext/CuYao/src/register.jl
ext/CuYao/test/instructs.jl

Update CUDA version

---

docs/src/examples/4.shor-algorithm/main.jl

Corrected minor spelling mistakes in the Shor algorithm example documentation for improved clarity.

Fix spelling mistakes in Shor algorithm example

---

lib/YaoBlocks/src/autodiff/chainrules_patch.jl
lib/YaoBlocks/test/autodiff/chainrules_patch.jl

Fix issue 545 - autodiff with batched-arrayreg

---

lib/YaoBlocks/src/composite/chain.jl
lib/YaoBlocks/src/composite/tag/cache.jl
lib/YaoBlocks/test/composite/chain.jl

Fix Issue 549: chain block constructor bug

---

lib/YaoBlocks/src/abstract_block.jl
lib/YaoBlocks/src/primitive/phase_gate.jl
lib/YaoBlocks/src/primitive/rotation_gate.jl
lib/YaoBlocks/src/primitive/shift_gate.jl
lib/YaoBlocks/test/abstract_blocks.jl

Fix issue 480 - rendering random parameters for rotation gates properly

---

lib/YaoPlots/src/vizcircuit.jl
lib/YaoPlots/test/vizcircuit.jl

Fix YaoPlots visualization of Measure block
